# fly.toml app configuration file generated for transit-redis-proud-shape-7901 on 2024-04-16T09:39:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'busfinder-redis'
primary_region = 'cdg'
kill_signal = 'SIGTERM'
kill_timeout = 10

[build]
  image = 'flyio/redis:6.2.6'

[mounts]
  source = 'redis_server'
  destination = '/data'

[[vm]]
  memory = '256m'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'
